### ISSUE TITLE
problem compiling mono (on ARCH Linux)

### ISSUE THREAD

**Issue by OlegHahm** [emul8/emul8#1]
I tried to install the mono according to the README on my ARCH Linux (Linux 4.2.3-1-ARCH, gcc (GCC) 5.2.0). It fails during the `make`-run with the following message:
```
Making all in mini
make[3]: Entering directory '/home/oleg/git/mono/mono/mini'
make  all-am
make[4]: Entering directory '/home/oleg/git/mono/mono/mini'
  CCLD     mono-boehm
./.libs/libmini-static.a(libmini_static_la-mini.o): In function `mono_get_jit_tls_offset'
/home/oleg/git/mono/mono/mini/mini.c:2666: undefined reference to `mono_jit_tls'
/home/oleg/git/mono/mono/mini/mini.c:2666: undefined reference to `mono_jit_tls'
collect2: error: ld returned 1 exit status
Makefile:1353: recipe for target 'mono-boehm' failed
```

Any ideas what could be missing?

**Comment by konrad-kruczynski** [comment]
Hello OlegHahm,
is according to README means that you've checked out the recommended revision? We wonder since boehm is rather obsolete (but maybe was still built in this version).

BTW, congratulations for being the first one to post an issue on the emul8 github!

**Comment by OlegHahm** [comment]
> is according to README means that you've checked out the recommended revision? We wonder since boehm is rather obsolete (but maybe was still built in this version).

Yes, I did this. But in a first attempt I missed that step, so I might need to do a `make clean` or so.

> BTW, congratulations for being the first one to post an issue on the emul8 github!

Thanks! ;)

**Comment by konrad-kruczynski** [comment]
Thanks for the information. We'll try to investigate the issue on ARCH Linux. In the meantime you could try to disable Boehm GC completely. You can do it using ``--disable-boehm`` switch added to ``autoconf`` command.

**Comment by OlegHahm** [comment]
Now I run into this:
```
  CXXLD    libmini-static.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       mono_sgen-main-sgen.o
  CCLD     mono-sgen
./.libs/libmini-static.a(libmini_static_la-mini.o): In function `mono_get_jit_tls_offset'
/home/oleg/git/mono/mono/mini/mini.c:2666: undefined reference to `mono_jit_tls'
/home/oleg/git/mono/mono/mini/mini.c:2666: undefined reference to `mono_jit_tls'
../../mono/metadata/.libs/libmonoruntimesgen-static.a(libmonoruntimesgen_static_la-sgen-alloc.o): In function `create_allocator'
/home/oleg/git/mono/mono/metadata/sgen-alloc.c:763: undefined reference to `tlab_next_addr'
collect2: error: ld returned 1 exit status
```

**Comment by konrad-kruczynski** [comment]
I see. We probably have to choose new recommended mono commit. After doing basic tests, it seems that the current tip, namely 4822ed5b92088c4a9b560c454dfff6dc35665197 looks promising. Could you try it?

**Comment by OlegHahm** [comment]
That seems to have helped.

**Comment by OlegHahm** [comment]
After installing mono and trying to bootstrap emul8, I got:
```
Cloning into 'External/Migrant'...
remote: Counting objects: 4310, done.
remote: Total 4310 (delta 0), reused 0 (delta 0), pack-reused 4310
Receiving objects: 100% (4310/4310), 1.66 MiB | 99.00 KiB/s, done.
There was an error while generating solution.
```
I guess this is an unrelated issue, so this one can probably be closed.

Thanks for the help.

**Comment by OlegHahm** [comment]
I tried to continue with the build process ignoring this error (may be a false positive anyway) and after figuring out that `zip` is also required as a prerequisite I got it compiling! :fireworks:

**Comment by farnerup** [comment]
I have the exact same problem with ubuntu 15.10.
4822ed5b92088c4a9b560c454dfff6dc35665197 seems to work.

**Comment by PiotrZierhoffer** [comment]
@OlegHahm, @farnerup - we have updated the recommended version in the docs. It is now 37f2657ac778d3934a1b3245076849816ff9e6f9.

And we have verified it compiling on Arch.
