### ISSUE TITLE
Missing namespaces (Gtk, etc) on OS X build

### ISSUE THREAD

**Issue by danellis** [emul8/emul8#123]
I've installed the official Mono package and the dependencies from Homebrew, but when I build I get lots of errors like the following:

```Xwt.GtkBackend/Gtk2Extensions.cs(33,41): error CS0246: The type or namespace name `Gtk' could not be found. Are you missing an assembly reference?```

Latest Mono on OS X 10.11.5, building from bda3350.

**Comment by konrad-kruczynski** [comment]
Thank you for report.
I have just done a fresh installation of OS X on a virtual machine and followed the instructions from README (I ran `bootstrap -a`). Everything seems to be OK. What do you mean by official mono package? Is it from homebrew or the mono project website? You should use the latter.

**Comment by danellis** [comment]
I did install it from the web site, but it turns out I already had an older mono package installed from Homebrew as well. Thanks for the tip about that -- it builds now.
