### ISSUE TITLE
Error building emul8 with '--console' option

### ISSUE THREAD

**Issue by aureliocano** [emul8/emul8#137]
Hi,

I am trying to build emul8 in a Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-108-generic x86_64) machine with '--console' flag and it seems that doesn't accept it:

`./build.sh --console`

`Invalid option: --`

Thanks

**Comment by PiotrZierhoffer** [comment]
Hi

Thank you for your report. It is actually a bug in the documentation - it's an old option, already removed.

Please refer to the updated README.

Building process is console-based, so no windows will pop up.
