### ISSUE TITLE
Environment variables in scripts

### ISSUE THREAD

**Issue by basilfx** [emul8/emul8#140]
I cannot find out how to use environment variables inside scripts. Is there an easy way to do so?

I tried to fiddle with the Python command, but I keep getting tokenization errors:

```
python "from System import Environment"
python "elf_file = Environment.GetEnvironmentVariable('ELFFILE')"

$binary = `python "print elf_file"`
```

**Comment by basilfx** [comment]
For [RIOT-OS](https://github.com/RIOT-OS/RIOT/pull/7945) I currently work-around this issue (?) by generating another script that includes the actual script.

**Comment by PiotrZierhoffer** [comment]
We actually have a builtin function for that.

    $binary=`get_environ ELFFILE`

should do the trick.
