### ISSUE TITLE
gtk-sharp not detected before build

### ISSUE THREAD

**Issue by John-K** [emul8/emul8#72]
I'm building on CentOS 7 and the build errors out because the mono gtk-sharp project isn't installed.

After downloading and manually patching up gtk-sharp (glib.h weirdness), it compiles fine and then so does emul8

**Comment by PiotrZierhoffer** [comment]
Did that happen despite having gtk-sharp installed via CentOS packet manager? On Debian-like systems mono-complete usually solves the issue.

To avoid the you can run ./bootstrap.sh and select the following options:

* leave the directories to scan unchanged (default: ".")
* select "Custom" solution file
* choose "CLI.csproj" as UI (the only version for now)
* choose all the architectures you'd like (the fewer you choose, the faster the build)
* choose all extension libraries WITHOUT VideoAnalyzerExtension
* from the "Plugins" you can choose only SampleCommandPlugin and TracePlugin and (others require gtk-sharp)
* from the next two screens you don't have to choose anything.

This should allow you to compile even without gtk-sharp installed.

**Comment by pgielda** [comment]
We have added gtk-sharp2 to dependencies. Thanks for reporting the issue.
