### ISSUE TITLE
emul8 cannot run from Linux CLI

### ISSUE THREAD

**Issue by John-K** [emul8/emul8#73]
I'm trying to run emul8 from a ssh session on CentOS7 and I get the following error:
Fatal error:
Could not start terminal. Possible config values: XTerm, Putty, GnomeTerminal

TERM is set to xterm-256color

**Comment by karol-arndt** [comment]
Have you tried starting run.sh with the --console parameter? 
By default, Emul8 opens up another terminal window, and you'd need to run X over SSH - and have one of the supported terminal apps installed.

**Comment by PiotrZierhoffer** [comment]
Could you provide some more information? Do you have xterm/putty/gnome-terminal installed on the target system?

Please try to use ssh -X or -Y, should help.

**Comment by John-K** [comment]
Running with --console works. I didn't see this in the documentation or commandline help

**Comment by PiotrZierhoffer** [comment]
The option is described in run.sh --help-cli - these are the options specific for user interface. It's probably not the easiest thing to find, we'll have to tweak it.
